name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/myvars.env
runs:
  using: "composite"
  steps:

    - name: Update environment file with 'run_id' value    
      run: |
        echo "RUNID = ${{github['run_id']}}"  >> ./.github/variables/myvars.env
        cat 
      shell: bash ./.github/variables/myvars.env

    - run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash