name: myworkflow
on:
    workflow_dispatch:

env:  
    #MYVAR1:
    #MYVAR2:        
    GITHUB_CONTEXT: ${{ toJSON(github) }}
         
jobs: 
    deploy:
      runs-on: ubuntu-latest
      environment: DEV
      
      steps:
        - uses: actions/checkout@v3
        - name: Set Environment Variables
          uses: ./.github/actions/setvars
          with:
            varFilePath: ./.github/variables/myvars.env

        - name: Update environment file with 'run_id' value
          run: echo "runid = ${{github['run_id']}}"  > ./.github/variables/myvars2.env
          
        - name: Display Environment variables
          run: |
            echo "${{env.MYVAR1}}"  
            echo "${{env.MYVAR2}}" 
            echo "${{env.run_id}}"  