name: myworkflow
on:
    workflow_dispatch:

env:  
    #MYVAR1:
    #MYVAR2:        
    GITHUB_CONTEXT: ${{ toJSON(github) }}
         
jobs: 
    deploy:
      runs-on: ubuntu-latest
      environment: DEV
      
      steps:
        - uses: actions/checkout@v3
        - name: Set Environment Variables
          uses: ./.github/actions/setvars
          with:
            varFilePath: ./.github/variables/myvars.env
        
        # - name: Update environment file with 'run_id' value    
        #   run: |
        #     echo "RUNID = ${{github['run_id']}}"  >> ./.github/variables/myvars.env

        - name: Display Environment variables
          run: |
            echo "${{env.MYVAR1}}"  
            echo "${{env.MYVAR2}}"
            echo "${{env.RUNID}}"   